[package]
name = "cone-volume"
version = "0.1.0"
authors = ["egrzeszczak <ernest.grzeszczak@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
